#!/usr/bin/env python3
"""Draw the ActionCache marks as vector geometry.

    python3 site/tools/gen-marks.py

Writes two files, both committed. This script exists so the geometry is
reproducible and reviewable, not so it can run at build time.

    site/assets/ac-wordmark.svg   the hero wordmark, currentColor
    site/assets/ac-mark.svg       the compact navbar mark, currentColor

Why this exists: resources/banner.svg draws the banner as twelve <text> lines
of box-drawing characters. That renders correctly only where the reader has a
monospace font carrying those glyphs; anywhere else the letters come out as
tofu boxes or shear into offset blocks. It also cannot take a colour from the
page, because an <img> has no access to currentColor and an inlined <style>
with a bare `text {}` rule would leak to every other SVG on the page.

ART below is that banner transcribed character for character, so what is drawn
here is the same banner and not a redesign.

The art is a fixed character grid, so the conversion is mechanical. The
box-drawing characters are a double line, which at any size this is actually
displayed reads as one stroke -- so each is drawn as a single bar of BAR
thickness, which is what those characters are already trying to look like.
"""

import pathlib

# The ACTION and CACHE banners, transcribed from resources/banner.svg.
ACTION = [
    " █████╗  ██████╗████████╗██╗ ██████╗ ███╗   ██╗",
    "██╔══██╗██╔════╝╚══██╔══╝██║██╔═══██╗████╗  ██║",
    "███████║██║        ██║   ██║██║   ██║██╔██╗ ██║",
    "██╔══██║██║        ██║   ██║██║   ██║██║╚██╗██║",
    "██║  ██║╚██████╗   ██║   ██║╚██████╔╝██║ ╚████║",
    "╚═╝  ╚═╝ ╚═════╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝",
]

CACHE = [
    " ██████╗ █████╗  ██████╗██╗  ██╗███████╗",
    "██╔════╝██╔══██╗██╔════╝██║  ██║██╔════╝",
    "██║     ███████║██║     ███████║█████╗  ",
    "██║     ██╔══██║██║     ██╔══██║██╔══╝  ",
    "╚██████╗██║  ██║╚██████╗██║  ██║███████╗",
    " ╚═════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝",
]

# One monospace cell. 3:5 is roughly a terminal cell, which is the proportion
# the art was drawn for -- at 1:1 the letters come out squat.
CELL_W = 12.0
CELL_H = 20.0

# The thickness of a box-drawing stroke, as a fraction of the cell. The source
# glyphs are double lines; at the sizes these marks are displayed the gap
# between the two lines is under a pixel, so one bar of this weight is both
# what it looks like and what survives being scaled down.
BAR = 0.34

# One cell of padding around the art.
MARGIN = 1


def cell_rects(char, col, row):
    """The rectangles one character contributes, in cell-relative units."""
    x, y = col * CELL_W, row * CELL_H
    w, h = CELL_W, CELL_H
    bw, bh = w * BAR, h * BAR          # bar thickness, horizontal and vertical
    cx, cy = x + (w - bw) / 2, y + (h - bh) / 2   # centred bar origin

    if char == "█":
        return [(x, y, w, h)]
    if char == "║":
        return [(cx, y, bw, h)]
    if char == "═":
        return [(x, cy, w, bh)]
    # The corners are a half-bar to the centre plus a half-bar out the other
    # side, so a corner meeting its neighbour leaves no notch at the join.
    if char == "╔":
        return [(cx, cy, w - (cx - x), bh), (cx, cy, bw, h - (cy - y))]
    if char == "╗":
        return [(x, cy, cx - x + bw, bh), (cx, cy, bw, h - (cy - y))]
    if char == "╚":
        return [(cx, cy, w - (cx - x), bh), (cx, y, bw, cy - y + bh)]
    if char == "╝":
        return [(x, cy, cx - x + bw, bh), (cx, y, bw, cy - y + bh)]
    if char == " ":
        return []
    raise ValueError(f"no geometry for {char!r}")


def fmt(value):
    """Trim a float to the shortest form that still reads exactly."""
    return f"{value:.2f}".rstrip("0").rstrip(".")


def path_for(rows, col_offset=0.0, row_offset=0.0):
    """One path's worth of subpaths, all wound the same way.

    Every subpath winds clockwise so the default nonzero fill unions them.
    Adjacent cells share edges and the corner bars overlap their neighbours;
    under evenodd each of those overlaps would punch a hole in the letterform.
    """
    out = []
    for r, line in enumerate(rows):
        for c, char in enumerate(line):
            for (x, y, w, h) in cell_rects(char, c, r):
                x += col_offset * CELL_W
                y += row_offset * CELL_H
                out.append(
                    f"M{fmt(x)} {fmt(y)}"
                    f"L{fmt(x + w)} {fmt(y)}"
                    f"L{fmt(x + w)} {fmt(y + h)}"
                    f"L{fmt(x)} {fmt(y + h)}Z"
                )
    return "".join(out)


def svg(width, height, path, label, note):
    return (
        f"<!-- Generated by site/tools/gen-marks.py. Do not edit.\n"
        f"     {note} -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {fmt(width)} {fmt(height)}"\n'
        f'     fill="currentColor"\n'
        f'     role="img" aria-label="{label}">\n'
        f'  <path d="{path}"/>\n'
        f"</svg>\n"
    )


def main():
    assets = pathlib.Path(__file__).resolve().parent.parent / "assets"

    # --- the wordmark: ACTION over CACHE, CACHE centred under ACTION --------
    cols = max(len(line) for line in ACTION)
    cache_cols = max(len(line) for line in CACHE)
    indent = (cols - cache_cols) / 2          # 3.5 cells, as in the original

    path = (
        path_for(ACTION, MARGIN, MARGIN)
        + path_for(CACHE, MARGIN + indent, MARGIN + len(ACTION))
    )
    width = (cols + 2 * MARGIN) * CELL_W
    height = (len(ACTION) + len(CACHE) + 2 * MARGIN) * CELL_H
    (assets / "ac-wordmark.svg").write_text(
        svg(width, height, path, "ActionCache",
            "The hero wordmark: the README banner as geometry rather than text.")
    )

    # --- the compact mark: the A of ACTION and the C beside it --------------
    # The full wordmark is illegible at navbar height, and the first two
    # letters are the two words. Columns 0-15 of the ACTION rows are exactly
    # its A and C, so the mark is cut from the banner rather than redrawn.
    ac = [line[:16] for line in ACTION]
    mark_path = path_for(ac, MARGIN, MARGIN)
    mark_w = (16 + 2 * MARGIN) * CELL_W
    mark_h = (len(ac) + 2 * MARGIN) * CELL_H
    (assets / "ac-mark.svg").write_text(
        svg(mark_w, mark_h, mark_path, "ActionCache",
            "The compact mark: the banner's A and C, for the navbar, where the\n"
            "     full wordmark is illegible.")
    )

    print(f"wrote {assets/'ac-wordmark.svg'} ({fmt(width)}x{fmt(height)})")
    print(f"wrote {assets/'ac-mark.svg'} ({fmt(mark_w)}x{fmt(mark_h)})")


if __name__ == "__main__":
    main()
